### ISSUE TITLE
Split screens on Mac

### ISSUE THREAD

**Issue by nachocodoner** [SaraVieira/stuff-i-use#1]
Hello Sara! I find some of your stuff handy for my setup.

I just wanted to ask if you use a MAC utility to split your windows automatically in well-sized parts, such us happen by default in other operative systems. I remember attending one of your conferences and I think you did that somehow.

Thank you 😄

**Comment by SaraVieira** [comment]
Hey man !

yap, I use https://www.spectacleapp.com/ and I am pretty happy with it :)
