### ISSUE TITLE
Just asking a question.

### ISSUE THREAD

**Issue by sayemon10** [SaraVieira/stuff-i-use#2]
Why do you use Hyper as your terminal?
I mean what's is benefit over default Windows CMD/ PowerShell or Apple's default Terminal?

Hope I'll get answer?

**Comment by SaraVieira** [comment]
Hey !

I like things to be very customizable easliy and hyper offered me this and that's the main reason because it's not faster or anything


It does handle links very well and I can program in it since its all react and js :D

**Comment by sayemon10** [comment]
Thanks for answering my question.

bTw, you have nice webpage, with smart trick applied to find information. Liked it 🙂

**Comment by SaraVieira** [comment]
Thanks :D
